# Generated by Django 4.0.2 on 2022-03-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_rename_another_code_referral_another_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
