# Generated by Django 4.0.2 on 2022-03-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_referral_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
